### ISSUE TITLE
how to make this code work

### ISSUE THREAD

**Issue by luochenhuan** [jdeng/word2vec#1]
Hello!

I have struggled to implement C+11 on my Ubuntu, and successfully compiled your project by running
++ -g -o w2v -std=c++0x -Ofast -march=native -funroll-loops  main.cc  -lpthread (a little different than your doc cuz I want to use gdb for debugging)

However, when I run the project as ./w2v, it returns only

collecting [word] 0 sentences, 0 distinct words, 0 words
Segmentation fault (core dumped)

And I cannot input strings as the lines 62:74 indicate.

I am wondering if there is something wrong with my procedure or if I need to do other things.

Thank you in advance!

**Comment by jdeng** [comment]
Did you forget to put the file "text8" in your working directory? See below related code in main.cc

```
           // wget http://mattmahoney.net/dc/text8.zip
            std::ifstream in("text8");
            while (true) {
```
