### ISSUE TITLE
Why not negative sampling in word2vec?

### ISSUE THREAD

**Issue by siegfang** [jdeng/word2vec#2]
Hi! I have read the origin paper(Distributed Representations of Words and Phrases and Their Compositionality) for word2vec, I find the implementation of the negative sampling which is reported good for word embedding by Mikolov in his paper in, but you make it disable [line468](https://github.com/jdeng/word2vec/blob/master/word2vec.h#L468). 
Is that because good performance is able to achieve without negative sampling?

**Comment by jdeng** [comment]
Right. The performance improvement was not observed but I am not sure if my implementation is accurate.

**Comment by siegfang** [comment]
Recently I have realized word2vec in Java: https://github.com/siegfang/word2vec , and receive much help from you code, thank you:)
