### ISSUE TITLE
How to run the Github

### ISSUE THREAD

**Issue by muthiyanbhushan** [jdeng/word2vec#9]
Hello,

When we run a command provided in the main.cc file it generates a executable. Thats nice.

But, what parameters do I need to pass for training. 

Can you please specify details in readme file.

I am trying to run standard text8 corpus with 71291 vocab size.

Thanks.

**Comment by muthiyanbhushan** [comment]
Any comments ?

Thanks.

**Comment by jdeng** [comment]
Please take a look at main.cc around line 90: you need to download the training file, unzip it and put it into your directory.

```
// wget http://mattmahoney.net/dc/text8.zip
std::ifstream in("text8");
```

**Comment by muthiyanbhushan** [comment]
Thanks.
